# Generated by Django 4.0.8 on 2022-11-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ob', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
