# Generated by Django 4.1.2 on 2022-11-08 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ob', '0007_alter_question_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seoultable',
            options={'managed': True},
        ),
    ]
