# Generated by Django 4.1.2 on 2022-11-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ob', '0008_alter_seoultable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seoultable',
            options={'managed': False},
        ),
    ]
