# Generated by Django 4.1.2 on 2022-11-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ob', '0009_alter_seoultable_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CctvTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
