# Generated by Django 4.1.2 on 2022-11-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ob', '0010_cctvtable_resttable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cctvtable',
            name='name',
        ),
    ]
