# Generated by Django 4.1.2 on 2022-11-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ob', '0011_remove_cctvtable_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='resttable',
            name='food_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
